function e = fpEntry(stage, hash, summ, orderHash, selPID, success, latency)
%FPENTRY  Build one fingerprint-log entry with a FIXED set of fields, so the
%   entries concatenate into a struct array regardless of stage type. Stages
%   without a state summary (schedule, metrics) get NaN aggregates.
%
%   orderHash : MD5 of PIDs in ARRAY ORDER (fpOrderHash) -- '' if not provided.
%   selPID    : provider selected at this step -- '' if not provided.
%   success   : offload success/fail status of this step (0/1) -- NaN if N/A.
%   latency   : offload latency (ms) of this step -- NaN if N/A.
    if nargin < 3 || isempty(summ) || ~isstruct(summ)
        summ = struct('n',NaN,'sumRep',NaN,'nActive',NaN,'nWarning',NaN, ...
                      'sumBlackout',NaN,'sumWarnStk',NaN,'sumBlacklst',NaN,'nMalicious',NaN);
    end
    if nargin < 4 || isempty(orderHash), orderHash = ''; end
    if nargin < 5 || isempty(selPID),    selPID    = ''; end
    if nargin < 6 || isempty(success),   success   = NaN; end
    if nargin < 7 || isempty(latency),   latency   = NaN; end
    e = struct( ...
        'stage',       char(stage), ...
        'hash',        char(hash), ...
        'orderHash',   char(orderHash), ...
        'selPID',      char(selPID), ...
        'success',     double(success), ...
        'latency',     double(latency), ...
        'n',           summ.n, ...
        'sumRep',      summ.sumRep, ...
        'nActive',     summ.nActive, ...
        'nWarning',    summ.nWarning, ...
        'sumBlackout', summ.sumBlackout, ...
        'sumWarnStk',  summ.sumWarnStk, ...
        'sumBlacklst', summ.sumBlacklst, ...
        'nMalicious',  summ.nMalicious );
end
